### ISSUE TITLE
[NoLockScreen] Plugin drains battery faster?

### ISSUE THREAD

**Issue by itsminht** [TheOfficialFloW/VitaTweaks#4]
I can't tell for sure but it feels like after enabling this plugin, my vita's battery seems to drain a bit faster . Could it have something to do with the fact that the plugin is constantly running in the background making sure that the lockscreen is disabled .

Anyways I would just like to ask if this is a possibility or if you know anything about how the plugin affects battery life. Apologies if this turns out to be a non-issue and I'm wasting your time, feel free to just close this "issue".

**Comment by TheOfficialFloW** [comment]
Are you using sd2vita?

**Comment by TheOfficialFloW** [comment]
update your driver then.

**Comment by DigiOhhh** [comment]
I think the issue is actually related to old versions of gamesd.skprx or StorageMgr, since both of them have the infamous random wake-up glitch. But because of this plugin the screen will take longer to lock, whereas without NoLockScreen I guess it would require less time. 
In my case, I disabled the auto-lock function via RegistryEditor and this was probably the cause of my battery always getting completely drained.

**Comment by itsminht** [comment]
How did you completely disable the auto-lock function via RegistryEditor? Which registry did you edit and what value did you set it to? Is this the equivalent of "Enter Standby mode after x minutes" in the settings app? So after the registryedit your vita stays awake/on indefinitely until you manually press the power button?

I also quite don't follow how did disabling auto-lock fix your battery drainage issues? 

I was running latest version of storagemgr (v3.0 - which fixed wakeup issues) as well as the NoLockScreen plugin when I noticed that my battery drained a bit faster. I disabled NLS plugin and battery drain went back to normal. Again, I cannot be 100% certain as theres no way to accurately measure such a small change in battery drainage.

**Comment by Highthorn90** [comment]
I also noticed the battery draining while using this plugin. 
I'm using a ps vita 1004 (fat, oled) with firmware 3.60 henkaku, official memory card. 
When I had the nolockscreen plugin it seemed like it didn't go into sleep/standby properly, draining the battery 5% per hour. 
Since I uninstalled the plugin it doesn't even go down 1% overnight. 
So I just got used to the lockscreen, even though it doesn't really make sense on a gaming device, but it doesn't really bother me anymore. 

(I'm sorry to bump this old thread for my first post)
